# Copyright (C) 2023 Felix Huettner
#
# This file is part of DTRD.
#
# DTRD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# DTRD is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

name: test_and_release

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - main

jobs:
  test:
    name: Test and linting
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      ROCKSDB_LIB_DIR: /usr/lib/x86_64-linux-gnu

    steps:
      - uses: actions/checkout@v6

      # When rustup is updated, it tries to replace its binary, which on Windows is somehow locked.
      # This can result in the CI failure, see: https://github.com/rust-lang/rustup/issues/3029
      - run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile minimal

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - uses: Swatinem/rust-cache@v2

      - name: Install librocksdb
        run: |
          sudo apt update
          sudo apt install librocksdb8.9 librocksdb-dev

      - name: Cargo fmt
        run: cargo fmt --all -- --check
      - name: Cargo test
        run: cargo test
      - name: Cargo clippy
        run: cargo clippy

  release:
    name: Release
    needs: [test]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
